# 設定テンプレート（コピーして config.yaml として使用）

weights:
  upgrade: 4
  buyback_large: 5
  buyback_small: 3
  dividend_increase: 2
  split: 2
  big_order: 3
  partner: 2
  partner_tier1: 2
  approval_patent: 4
  kpi_surprise_low: 2
  kpi_surprise_high: 4
  negative_offering: -4
  lawsuit: -3
  deficit_widen: -2
  intraday_bonus: 1

thresholds:
  min_score: 4
  top_k: 10

feeds:
  tdnet: https://www.release.tdnet.info/rss/TDnet.xml
  prtimes: https://prtimes.jp/index.rdf
  valuepress: https://www.value-press.com/rss/index.rdf
  kyodo_pr: https://kyodonewsprwire.jp/feed/release
  dreamnews: https://www.dreamnews.jp/?action_rss=1
  newscast: https://newscast.jp/rss
  thebridge: https://thebridge.jp/feed
  itmedia_business: https://rss.itmedia.co.jp/rss/2.0/business.xml
  nhk_business: https://www3.nhk.or.jp/rss/news/cat5.xml
  nhk_economy: https://www3.nhk.or.jp/rss/news/cat6.xml
  # 企業IR RSS例を追加可能

collectors:
  # 追加データソース例: RSSプラグイン形式（feedsと同様の仕組みを別名で拡張可能）
  # - name: example_ir
  #   type: rss
  #   url: https://example.com/ir/feed.xml
  # 外部API対応コレクタは `type` に "モジュール:関数" または `kabu2.collectors` エントリポイント名を指定します。
  # - name: premium_source
  #   type: yourpkg.collectors.premium:collect
  #   token: YOUR_API_TOKEN

feeds_priority:
  tdnet: 1.5
  prtimes: 0.5
  kyodo_pr: 0.3
  valuepress: 0.2
  dreamnews: 0.2
  newscast: 0.2
  itmedia_business: -0.3
  nhk_business: -0.5
  nhk_economy: -0.5

feeds_ai:
  max_keys: 3
  fresh_hours: 12
  stale_penalty: 5.0
  repeat_penalty: 2.0
  history_weight: 0.5
  cooldown_hours: 4

storage:
  path: data/news.jsonl

notifier:
  slack:
    enabled: false
    webhook_env: SLACK_WEBHOOK_URL
    min_score: 6
    cooldown_min: 30
